# Generated by Django 3.2 on 2022-07-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersub',
            options={'ordering': ['subscribe_date'], 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
    ]
