# Generated by Django 3.2 on 2022-06-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220623_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[
                ('Yummy', 'Yummy'),
                ('Adriafil', 'Adriafil'),
                ('Scheppjes', 'Scheppjes'),
                ('New Fashion', 'Newfashion'),
                ('Other', 'Other')
            ], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, choices=[
                ('SuperFine (Baby, Fingering, Sock)', 'Super Fine'),
                ('Fine (Baby, Sport)', 'Fine'),
                ('Light (DK, Light, Worsted)', 'Light'),
                ('Meduim (Afgan, Aran, Worsted)', 'Meduim'),
                ('Bulky (Chunky, Craft, Rug)', 'Bulky'),
                ('Super Bulky (Bulky, Roving)', 'Super Bulky'),
                ('Jumbo (Jumbo, Roving)', 'Jumbo'),
                ('Other', 'Other')
            ], max_length=50, null=True),
        ),
    ]
