# Generated by Django 3.2 on 2022-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_other_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[
                ('Yummy', 'Yummy'), ('Adriafil', 'Adriafil'),
                ('Scheepjes', 'Scheepjes'),
                ('New Fashion', 'Newfashion'),
                ('Other', 'Other')
            ], max_length=20, null=True),
        ),
    ]
